"""add model relationships

Revision ID: 5e298b87e427
Revises: bc360df9d9d6
Create Date: 2026-07-17 13:45:50.071760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5e298b87e427'
down_revision: Union[str, Sequence[str], None] = 'bc360df9d9d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('companies', 'plan',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('companies', 'document_limit',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('companies', 'documents_used',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('documents', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('documents', 'file_path',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('documents', 'document_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('documents', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('documents', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.alter_column('users', 'firstname',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'lastname',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'lastname',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'firstname',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.alter_column('documents', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('documents', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('documents', 'document_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('documents', 'file_path',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('documents', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('companies', 'documents_used',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('companies', 'document_limit',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('companies', 'plan',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
